### ISSUE TITLE
Clouds take the colour of water

### ISSUE THREAD

**Issue by jmarucha** [unicornbloods/BeyondBeliefVanillaReborn#3]
Version: Minecraft 1.15.2 with OptiFine G1pre13 on W10
Hardware: GTX 1060 Mobile

The slider adjusting the color of water also changes the color of clouds. They have nasty cyan tint from the very beginning (also default water looks has super strong color, idk if it was intended). The slider for cloud color does nothing, as well as toggle for custom clouds.

**Comment by jmarucha** [comment]
![2020-04-12_17 35 36](https://user-images.githubusercontent.com/8832340/79073003-5a718c00-7ce4-11ea-8956-8a24f4f88d09.png)
![2020-04-12_17 36 01](https://user-images.githubusercontent.com/8832340/79073009-63625d80-7ce4-11ea-96bd-21c73095e484.png)

**Comment by unicornbloods** [comment]
Yea the default color is intentional for the water ( I am gonna change that today ) but the cloud thing is something to do with my matID assignment being weird. 
Thanks for the report! I am gonna close this thread and keep this issue to just https://github.com/unicornbloods/BeyondBeliefVanillaReborn/issues/4
